name: ci

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        if: github.ref_type == 'tag'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/login-action@v2
        if: github.ref_type == 'tag'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            ${{ github.repository_owner }}/nethack
            ghcr.io/${{ github.repository_owner }}/nethack
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}}
      - uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/ppc64le
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=nethack
          cache-to: type=gha,mode=max,scope=nethack
      - uses: docker/metadata-action@v4
        id: meta_x11
        with:
          images: |
            ${{ github.repository_owner }}/nethack-x11
            ghcr.io/${{ github.repository_owner }}/nethack-x11
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}}
      - uses: docker/build-push-action@v3
        with:
          context: x11
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta_x11.outputs.tags }}
          labels: ${{ steps.meta_x11.outputs.labels }}
          cache-from: type=gha,scope=x11
          cache-to: type=gha,mode=max,scope=x11
